### ISSUE TITLE
Tooltip shifting from the center 

### ISSUE THREAD

**Issue by AlmahaAlmalki** [replot/replot-map#32]
Hi @alisaono,

<img width="978" alt="screenshot 2018-01-22 13 30 34" src="https://user-images.githubusercontent.com/11076091/35237510-e1865e64-ff78-11e7-9353-c231c741a76d.png">

The tooltip in the map always shows starting from the lower left corner, not sure if I'm doing something that makes it shift or there's a bug. 

Thanks!

**Comment by alisaono** [comment]
The tooltip positions fine when I try with my examples locally.... @sanjaypojo Could it be the same issue we were having with network chart? Not 100% sure how you ended up fixing it.
https://github.com/MacroConnections/replot-network/issues/16

**Comment by alisaono** [comment]
@AlmahaAlmalki Also following up, if you need a quick fix, check if the div containing the map has 'text-align:center' style. If so, remove it, and it should resolve the issue for now.

**Comment by AlmahaAlmalki** [comment]
@alisaono I tried didn't work ;/!

**Comment by alisaono** [comment]
@AlmahaAlmalki hmmm can you share me the code for it? (including the divs containing the map and their styles)

**Comment by AlmahaAlmalki** [comment]
```
render () {
    
    let map = false
    if (this.state.dataset && this.state.dataset.length > 0) {
      map = <Map data={this.state.dataset}
        paths={WORLD}
        IDKey='code'
        weightKey='collaboration' 
        scale="log"
        colorRangeLow="#ffffff"
        colorRangeHigh="#4A46DA"
        tooltip={true}
        tooltipContents={this.fillTooltip}/>
    }

    return (
      <div className={'contant'}>
        <div className={'paddingGrid'}>&nbsp;</div>
        <div className={'visualization'}>{map}</div>
        <div className={'description'}>
          <h3 className={'sectionTitle'}>Collaborators based on Countries</h3>
          <h4 className={'descriptionText'}>This graph shows collaborators of {this.state.scholarName}  based on organization location</h4>
        </div>
      </div>
    )
  }
```
```

.contant {
  /*position: relative;*/
  background-color: #17202F;
  width:100%;
  height:80%;
  margin-top: 100px;
  /*margin-bottom: 200px;*/
  min-height: 500px;
  -webkit-box-shadow: 3px 1px 3px 5px #131A26;  /* Safari 3-4, iOS 4.0.2 - 4.2, Android 2.3+ */
  -moz-box-shadow:    3px 1px 3px 5px #131A26;  /* Firefox 3.5 - 3.6 */
  box-shadow:         3px 1px 3px 5px #131A26;  /* Opera 10.5, IE 9, Firefox 4+, Chrome 6+, iOS 5 */
}

.paddingGrid {
  display:inline-block;
  width: 20%;
  float:left;
}

.visualization {
  width: 60%;
  height: 100%;
  padding: 50px;
  float:left;
}

.description {
  background-color: #1E2739;
  width:20%;
  height: 100%;
  float:right;
  padding: 50px;
  /*height:25%;*/
  /*margin:10 auto;*/
  /*margin-top: 200px;*/
  right:0;
  top:0;
}
```

**Comment by alisaono** [comment]
hmm try removing 'float:left' from .visualization maybe? Let me know if that changes anything

**Comment by AlmahaAlmalki** [comment]
didn't change anything :|

**Comment by alisaono** [comment]
okay I'm honestly not sure exactly why, so just throwing out possible ideas... but maybe try adding 'text-align:left;' to  .visualization ?

**Comment by sanjaypojo** [comment]
@alisaono it might be much easier to debug this in person. Will be tough to figure out what's going wrong without having the code in front of us. @AlmahaAlmalki, maybe we can take a look after the group meeting?

**Comment by AlmahaAlmalki** [comment]
yes, don’t worry about it @alisaono. 
 thanks :)!!
