### ISSUE TITLE
Is there a way where I can add a title to the legend? 

### ISSUE THREAD

**Issue by AlmahaAlmalki** [replot/replot-map#36]

**Comment by alisaono** [comment]
@AlmahaAlmalki set showTitle={true} and legendTitle="YOUR_TITLE"

**Comment by alisaono** [comment]
E.g.
```<Legend values={this.state.values} shape="circle" showTitle={true} legendTitle="Countries" />```
Shows this:

![screen shot 2018-02-08 at 8 01 21 pm](https://user-images.githubusercontent.com/25045998/36006428-dbf34f08-0d0a-11e8-9e5d-188fc3cee30d.png)

**Comment by AlmahaAlmalki** [comment]
I’m using the legend included in the map. Does it have the same prop? In the code it doesn’t show

**Comment by alisaono** [comment]
Oh sorry I was thinking you meant the legend in replot-core. We don't have legend title prop for the map, but we can add one if you think that'd be useful...!

**Comment by AlmahaAlmalki** [comment]
I think we should add one to explain what the color scale represents.

**Comment by alisaono** [comment]
sure let's create a new Map prop and call it 'legendTitle' or something?

**Comment by AlmahaAlmalki** [comment]
@alisaono it would be great if this style of legend can be a part of replot-core. Also, just a design enhancement can we make the legend with only one rect and color it based on the gradient instead of using multiple reacts and coloring them individually.    

<img width="373" alt="screenshot 2018-02-14 17 18 31" src="https://user-images.githubusercontent.com/11076091/36231183-1f066d1c-11ab-11e8-8808-125cd692baa6.png">

Thanks!

**Comment by alisaono** [comment]
@AlmahaAlmalki I agree we should move the current map legend into the replot-core. We can definitely do the gradient. Do you think we should give options between the current rects vs gradient styles? Or do you think it's natural to only have the gradient option?

**Comment by AlmahaAlmalki** [comment]
Since you already wrote the code we could definitely make it as a style option :).
