### ISSUE TITLE
Change opacity for regions with no data

### ISSUE THREAD

**Issue by sanjaypojo** [replot/replot-map#38]
Currently, the regions with no data have the same color as the minimum. We need to also lower the opacity of these regions, so that they look different from regions that are at the minimum. (Basically `zero != null` type situation)

**Comment by alisaono** [comment]
Maybe by default, we can have a distinct pattern for no data region?

![images](https://user-images.githubusercontent.com/25045998/36271510-d19e9a52-124c-11e8-8d55-35162fd738a4.png)
^Okay this map looks ugly but you get the idea.

I think it will be easy for the user to notice they have regions without data this way. 

In addition to the default, we can have a prop like `noDataColor` so if the user has a specific color they want for the undefined regions, they can customize?

@sanjaypojo

**Comment by sanjaypojo** [comment]
`noDataColor` is a good idea, let's add that prop. I feel like we want to take the attention of the users away from regions without data, that's why we wanted to try out lowered opacity. Let's see what it looks like and then try out a pattern if the lowered opacity doesn't work?

@alisaono

**Comment by alisaono** [comment]
Sounds good! Ah I meant the user as in the one who's implementing the code (in case they don't realize they're missing data for some regions) but let's try out lowered opacity and see how it looks.
@sanjaypojo
