### ISSUE TITLE
Is there color function option?

### ISSUE THREAD

**Issue by AlmahaAlmalki** [replot/replot-map#41]
it seems there's no color function option, but I just wanted to make sure.

**Comment by alisaono** [comment]
There's no color function option for map right now @AlmahaAlmalki

**Comment by alisaono** [comment]
We could make one if you think that's useful

**Comment by AlmahaAlmalki** [comment]
If we gonna add more color scales methods I don't think we need it. But, for me to speed up the process I thought of creating my own color function and just pass them to Replot. Also, is there a way of hiding the legend?

**Comment by alisaono** [comment]
Okay if I have time this weekend, I can add color function as an option. Also right now we don't have an option to hide legend either, but we can add.
