### ISSUE TITLE
Map is not passing data 

### ISSUE THREAD

**Issue by AlmahaAlmalki** [replot/replot-map#42]
Hi @alisaono 

So I just updated replot map, and the coloring of the map is not working. It seems like the data is not begin passed for some reason.

<img width="1440" alt="screenshot 2018-02-28 12 35 54" src="https://user-images.githubusercontent.com/11076091/36802844-fb73528c-1c83-11e8-8f35-7b5a31b04bd9.png">

This's my code 

```
    if (this.state.dataset && this.state.dataset.length > 0) {
      map = <Map data={this.state.dataset}
        paths={WORLD}
        IDKey='code'
        weightKey='collaboration'
        scale='lin'
        colorRangeLow='#ffffff'
        colorRangeHigh='#4A46DA'
        noDataOpacity={0.1}
        legendTitle="Collaboration"
        tooltip={true}
        tooltipContents={this.fillTooltip}/>
    } 
```

Data

[{"country":"Germany","code":"DE","collaboration":0},{"country":"Philippines","code":"PH","collaboration":0},{"country":"Denmark","code":"DK","collaboration":0},
{"country":"India","code":"IN","collaboration":0},
{"country":"Spain","code":"ES","collaboration":0},
{"country":"Belgium","code":"BE","collaboration":1},
{"country":"Chile","code":"CL","collaboration":1.584962500721156},{"country":"Canada","code":"CA","collaboration":2},
{"country":"United States","code":"US","collaboration":4.087462841250339}]

**Comment by alisaono** [comment]
Ah it's probably because we've updated `IDKey` prop to `geoCode`... Try changing that and let me know if the issue persists! @AlmahaAlmalki

**Comment by AlmahaAlmalki** [comment]
I don't know how I didn't see it, thanks @alisaono

**Comment by alisaono** [comment]
No worries! Closing the issue.
